version: '3.8'
services:
  node:
    image: xmtp/node-go:latest
    platform: linux/amd64
    environment:
      - GOWAKU-NODEKEY=8a30dcb604b0b53627a5adc054dbf434b446628d4bd1eccc681d223f0550ce67
    command:
      - --store.enable
      - --store.db-connection-string=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable
      - --store.reader-db-connection-string=postgres://postgres:xmtp@db:5432/postgres?sslmode=disable
      - --mls-store.db-connection-string=postgres://postgres:xmtp@mlsdb:5432/postgres?sslmode=disable
      - --mls-validation.grpc-address=validation:50051
      - --api.enable-mls
      - --wait-for-db=30s
      # Disable authn until we have reliable support for generating auth tokens
      # - --api.authn.enable
    ports:
      - 5555:5555
      - 5556:5556
    depends_on:
      - db
    healthcheck:
      test: ['CMD', 'lsof', '-i', ':5556']
      interval: 3s
      timeout: 10s
      retries: 5

  validation:
    image: ghcr.io/xmtp/mls-validation-service:main
    platform: linux/amd64

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp

  mlsdb:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: xmtp

  js:
    restart: always
    platform: linux/amd64
    depends_on:
      node:
        condition: service_healthy
    build: ./test

  upload-service:
    build: ./upload-service
    ports:
      - 4567:4567

  caddy:
    image: caddy:latest
    ports:
      - '443:443'
    volumes:
      - ./upload-service/Caddyfile:/etc/caddy/Caddyfile
      # - ./upload-service/data/data:/data
      # - ./upload-service/data/config:/config
